[[ITSOL_2]]
arch = "aarch64"
git-tree-sha1 = "951eda8754f861a8f410fbddcb501b0c57412d4c"
libgfortran_version = "5.0.0"
os = "macos"

    [[ITSOL_2.download]]
    sha256 = "e0ff278b0936ccd09fc3ef04137cdd9452f871fbc7430c67d4c6b86b4c5599b1"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.2+0/ITSOL_2.v0.1.2.aarch64-apple-darwin-libgfortran5.tar.gz"
[[ITSOL_2]]
arch = "aarch64"
git-tree-sha1 = "af4ede6da9c9f67fe557be663c053fd02c37e93e"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "5d28563a76482e8769615abf013e149232b772992a4ee1dbf1c9388a5aae3136"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.2+0/ITSOL_2.v0.1.2.aarch64-linux-gnu-libgfortran3.tar.gz"
[[ITSOL_2]]
arch = "aarch64"
git-tree-sha1 = "070aa929bbaa8d7827f64ec9990b4c200af23ded"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "0daa7a64b019471093f9ab70e91ac5caf9b26b9259a3f03ec51e1cef3d0aff46"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.2+0/ITSOL_2.v0.1.2.aarch64-linux-gnu-libgfortran4.tar.gz"
[[ITSOL_2]]
arch = "aarch64"
git-tree-sha1 = "3b145ab1de22726579280e387cebbb10b89565d5"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "c537a709d42374fbac5d0295842b46bea4f6974a8aa30b522361a964c5693f05"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.2+0/ITSOL_2.v0.1.2.aarch64-linux-gnu-libgfortran5.tar.gz"
[[ITSOL_2]]
arch = "aarch64"
git-tree-sha1 = "f2d9c6f5c52bf2ec185d0f7bac16d17e57aa36b7"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "2db22d0f67fe8c8d68267754e588c545bf23bd6c8da8b23c9242c847c5916cf0"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.2+0/ITSOL_2.v0.1.2.aarch64-linux-musl-libgfortran3.tar.gz"
[[ITSOL_2]]
arch = "aarch64"
git-tree-sha1 = "9349172c6c932f7454b3a784c170b97b32a30ae6"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "27ec92f53842b56d82160bdb6f6f0a816cd04e79acd8a36f5dbaac98c60d1905"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.2+0/ITSOL_2.v0.1.2.aarch64-linux-musl-libgfortran4.tar.gz"
[[ITSOL_2]]
arch = "aarch64"
git-tree-sha1 = "12627d92b5ba2fdc88ee617589075ce2bc2130a8"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "8fdfe79912e4f1d98a888e3365bcd21fb5a9bc761e35d72d0a8f870228f53371"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.2+0/ITSOL_2.v0.1.2.aarch64-linux-musl-libgfortran5.tar.gz"
[[ITSOL_2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "aac6c2f46cf3a565224891237a18bb2c87858321"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "78cde8c45bf924477b56478bbbe1e5175e2c988c0df73e7675fb7f7c284f4d56"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.2+0/ITSOL_2.v0.1.2.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[ITSOL_2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ea23e962a67ee1c0eb4b5f8b885cfd1452d1aa2e"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "f71b61d293038903846c5e21f8e283e36047890326f90560e0a74b4230d7997f"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.2+0/ITSOL_2.v0.1.2.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[ITSOL_2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "87b6090d7dca2c13ecbcd04a2c0d2627f8fcfa63"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "ec4ce47dfe02e97f41e8a19656b8b1f92aa19d0398eea3eb634a09a01f090f45"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.2+0/ITSOL_2.v0.1.2.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[ITSOL_2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ad1c89bb42e3a08a68b41e85179ea644484522ba"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "13de80ac355c28278ae6ade4f2f6cba0924ae3cf8c28a4b3c316bc2450509d66"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.2+0/ITSOL_2.v0.1.2.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[ITSOL_2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "765edfc3beff4b366ea1e06439e9ed58c593226c"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "bb3da68b3fbf169edd7f9c094c48389e6392dd9d28f8b34710c95ed3aacb7a5c"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.2+0/ITSOL_2.v0.1.2.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[ITSOL_2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ba25c3da2ab86690317300a8f18bcdf05d965c40"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "71d91497cafb5d05bec66139aea1a7f8fc921847ebda6f396c1db23efd1d090d"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.2+0/ITSOL_2.v0.1.2.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[ITSOL_2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5d7f46f23baa0e9ba857bdb8d611dc4cd976144d"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "ad670439ca7129d2538ef70a3379596ca532c8222578647bcace1408201a867d"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.2+0/ITSOL_2.v0.1.2.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[ITSOL_2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "26ed9c58b19d8797564f62457e3671a629de7ddc"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "1ec04e5e7344a396eaa6a9ef196013f6dd10fbca23ed542f14907129362b2577"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.2+0/ITSOL_2.v0.1.2.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[ITSOL_2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "51995295bd5bcb4465797d23776fa67430955abf"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "6430eb6873e7c90d5f59805dca8a260ae39c586eb277d3de493b8962b5a6d572"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.2+0/ITSOL_2.v0.1.2.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[ITSOL_2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "acfa78c4fa361c41c644b0565968e6071e89a766"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "f5bea9e8eb78104b3a2953fe9ecd98906da0abc839d6b189fe140f5fff9dc2f2"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.2+0/ITSOL_2.v0.1.2.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[ITSOL_2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f6154b967f5f9ca91332976367fb7f62f962d698"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "d7a3d4394195aa2b2189117c35f6f5db53ba621a2d74f23e651a970ca4b78893"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.2+0/ITSOL_2.v0.1.2.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[ITSOL_2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2fab0db330eb144d875921eba142fd279a5ad0f4"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "5c179bda7f80c2855aa203f97c6b9d4e0a5880e4b2c507f944e46e291ef63180"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.2+0/ITSOL_2.v0.1.2.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[ITSOL_2]]
arch = "i686"
git-tree-sha1 = "f9a436300ea340ad0ec79f9f0adbeb6c6480d254"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "3f3639afce5b81c63afca575bfa0af9c3f6fdaabadca888838e770e6d08778ea"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.2+0/ITSOL_2.v0.1.2.i686-linux-gnu-libgfortran3.tar.gz"
[[ITSOL_2]]
arch = "i686"
git-tree-sha1 = "ffb7376c1c7525f7827db1a15f14bf29d48260b0"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "3ff3c6a441bcd45f1874edc1331af4230bf5cc0b4220ffdbc1c13b0ca213922b"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.2+0/ITSOL_2.v0.1.2.i686-linux-gnu-libgfortran4.tar.gz"
[[ITSOL_2]]
arch = "i686"
git-tree-sha1 = "faf4bce5be3761d2355dcdd872a6ff9357475884"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "b492d30bbceb7b96b81983c81cb76cb2f463932b83be46704f8d63574ff94deb"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.2+0/ITSOL_2.v0.1.2.i686-linux-gnu-libgfortran5.tar.gz"
[[ITSOL_2]]
arch = "i686"
git-tree-sha1 = "ace216c068ef2090d60562e1eda60f4a7c5ba8ab"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "e403e05d87a9e0fd708a659ef21ab2567170350518dc52c4be681e5e16272798"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.2+0/ITSOL_2.v0.1.2.i686-linux-musl-libgfortran3.tar.gz"
[[ITSOL_2]]
arch = "i686"
git-tree-sha1 = "3d257d76d98f01468be6ea3374739c7b63fef50d"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "6b8ea7cea78228de040fe0c831ca4809897dea64705fb6a54ca42c53ef99a81f"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.2+0/ITSOL_2.v0.1.2.i686-linux-musl-libgfortran4.tar.gz"
[[ITSOL_2]]
arch = "i686"
git-tree-sha1 = "4ace1a4ab9a299921179118afab0388d954a858c"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "d654c84063ae3042d0b7a6d88e8c3d86f11a6d94f91e56028b01fa6d622120a5"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.2+0/ITSOL_2.v0.1.2.i686-linux-musl-libgfortran5.tar.gz"
[[ITSOL_2]]
arch = "i686"
git-tree-sha1 = "83ef9850c7caa98a77d1c923931ddf851877ac04"
libgfortran_version = "3.0.0"
os = "windows"

    [[ITSOL_2.download]]
    sha256 = "cb57a2c0c4ccdfef529e7536afa0714f78822c6a9177a5d849a6915b6ccf6b38"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.2+0/ITSOL_2.v0.1.2.i686-w64-mingw32-libgfortran3.tar.gz"
[[ITSOL_2]]
arch = "i686"
git-tree-sha1 = "182a85a3963191e5421db1d85e2ff0c495019d5f"
libgfortran_version = "4.0.0"
os = "windows"

    [[ITSOL_2.download]]
    sha256 = "ce74b6bb904c779974e8558b214c7113b7637cb5a5d225a22322b42620c2789a"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.2+0/ITSOL_2.v0.1.2.i686-w64-mingw32-libgfortran4.tar.gz"
[[ITSOL_2]]
arch = "i686"
git-tree-sha1 = "2700c24580b48f4fd01b3876cf636cc38bddcef5"
libgfortran_version = "5.0.0"
os = "windows"

    [[ITSOL_2.download]]
    sha256 = "22312164d7b2c0e0ffbd4b717c449c767b07f8b4df32ca8a2b2d884092f661ad"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.2+0/ITSOL_2.v0.1.2.i686-w64-mingw32-libgfortran5.tar.gz"
[[ITSOL_2]]
arch = "powerpc64le"
git-tree-sha1 = "bdaa5dbd7ce9cb4e0db416e55e4416f9c3e30803"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "8f4f489a9af383cd22ee3ae217338f9ba01da5e35b073dea07e33cf98b24bf36"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.2+0/ITSOL_2.v0.1.2.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[ITSOL_2]]
arch = "powerpc64le"
git-tree-sha1 = "30bb617c04ba1e853fb362c28643072f980e0083"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "d2c4c562805befc96825e2d5d82746964eabf337e4a66e18eee57d22ef0aacf5"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.2+0/ITSOL_2.v0.1.2.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[ITSOL_2]]
arch = "powerpc64le"
git-tree-sha1 = "f99ab8899e8af9af0eeec102ef4a865c4b7aae48"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "8b580ff6f1d0a72132ef599fb3348474e59eaa4b615fd0c06c6630206ca981b1"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.2+0/ITSOL_2.v0.1.2.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[ITSOL_2]]
arch = "x86_64"
git-tree-sha1 = "014800ac64c5a10992e3ea41b6a931b6eaefda12"
libgfortran_version = "3.0.0"
os = "macos"

    [[ITSOL_2.download]]
    sha256 = "dd04471edb8b17c64eb0e5542efbfbaf7d832b1c3807e9fe0410b673f96b733a"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.2+0/ITSOL_2.v0.1.2.x86_64-apple-darwin-libgfortran3.tar.gz"
[[ITSOL_2]]
arch = "x86_64"
git-tree-sha1 = "f1be6474b6682603c1cf3e440b2f20cc49927119"
libgfortran_version = "4.0.0"
os = "macos"

    [[ITSOL_2.download]]
    sha256 = "4f5b5316cc54219b3083149b77bf050f18f2f0316b8685b8e23aad6d339e3246"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.2+0/ITSOL_2.v0.1.2.x86_64-apple-darwin-libgfortran4.tar.gz"
[[ITSOL_2]]
arch = "x86_64"
git-tree-sha1 = "06d29abb43f0035429b21a365bb948c571669421"
libgfortran_version = "5.0.0"
os = "macos"

    [[ITSOL_2.download]]
    sha256 = "0fa60cce67971f4183d5fa18c4e5cb47c140d5511a7a68c9f09c21a10c481595"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.2+0/ITSOL_2.v0.1.2.x86_64-apple-darwin-libgfortran5.tar.gz"
[[ITSOL_2]]
arch = "x86_64"
git-tree-sha1 = "e46f945b7022d85ea7921827c40efb35602a4f8b"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "c8b568f762d0f2da878d53f6f67869b696b41cc3f27bd6b4906200bde056d8d5"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.2+0/ITSOL_2.v0.1.2.x86_64-linux-gnu-libgfortran3.tar.gz"
[[ITSOL_2]]
arch = "x86_64"
git-tree-sha1 = "e7a987fafd6e7cc08daab535b29153d73a8cc311"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "bd00195548706028d32bb6b043b34ad9580c04850afa33e28be0b0acc657624e"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.2+0/ITSOL_2.v0.1.2.x86_64-linux-gnu-libgfortran4.tar.gz"
[[ITSOL_2]]
arch = "x86_64"
git-tree-sha1 = "4873550833276074f67c89df51b6eb155d3e199e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "d7dab97b3d760d1d17d33aded40aa88d96fa5fd0d0150c9212722dff62f3399a"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.2+0/ITSOL_2.v0.1.2.x86_64-linux-gnu-libgfortran5.tar.gz"
[[ITSOL_2]]
arch = "x86_64"
git-tree-sha1 = "3ac15f9aed834e5cd45d7c7f83efacef1ad05abf"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "9668e6297ac163c397fbb28964d8dbca962694a99757d7fdf5ef678efeb4df13"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.2+0/ITSOL_2.v0.1.2.x86_64-linux-musl-libgfortran3.tar.gz"
[[ITSOL_2]]
arch = "x86_64"
git-tree-sha1 = "3e995582fb74ead94aac302a689ece35a7d61e40"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "74e1af3c4a2aada6bcea5a30e6c599b7d28881b02c5668fef7925ad46e0ed7ff"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.2+0/ITSOL_2.v0.1.2.x86_64-linux-musl-libgfortran4.tar.gz"
[[ITSOL_2]]
arch = "x86_64"
git-tree-sha1 = "c223f2e9ac395e3332e8a5aa249529d7082a84b1"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "5b9666c328a9c388a9a01c3e728c2ce5a4cc48eca33fce8cd21e62187985666f"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.2+0/ITSOL_2.v0.1.2.x86_64-linux-musl-libgfortran5.tar.gz"
[[ITSOL_2]]
arch = "x86_64"
git-tree-sha1 = "54fc6a21039f5747437f0d5974a7855053ee7308"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[ITSOL_2.download]]
    sha256 = "a40a729bd88da508e8448655b73348c3295a02a838d5a519cfdd71353490bcf3"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.2+0/ITSOL_2.v0.1.2.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[ITSOL_2]]
arch = "x86_64"
git-tree-sha1 = "1e1a91f78792c518f482e4c212d11bc34e9a3a06"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[ITSOL_2.download]]
    sha256 = "45896bd36fbfcb044f24eb3631e83516b7a22f88761625391b45a619eea03c14"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.2+0/ITSOL_2.v0.1.2.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[ITSOL_2]]
arch = "x86_64"
git-tree-sha1 = "ea3b610b4744247b77fcc4460abd31cd0a7ad866"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[ITSOL_2.download]]
    sha256 = "400c27adaddf97dd110d8d7ae9010b4669c1da174ae341ad4000727489c56886"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.2+0/ITSOL_2.v0.1.2.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[ITSOL_2]]
arch = "x86_64"
git-tree-sha1 = "f3ea37fa82ebfbbbf567e38b34ad1eb95bf1ecbf"
libgfortran_version = "3.0.0"
os = "windows"

    [[ITSOL_2.download]]
    sha256 = "c0e2ef44867eb43be341ddb33097963f81de4f2b5feec084214940c068fbc8c0"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.2+0/ITSOL_2.v0.1.2.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[ITSOL_2]]
arch = "x86_64"
git-tree-sha1 = "2e8dfd4efbf2ae2727db6fb072be6847b6364c2f"
libgfortran_version = "4.0.0"
os = "windows"

    [[ITSOL_2.download]]
    sha256 = "2cdadfa3fe2599540d681d1c12e4ebfab02ad89611898012a63a4be977fdbda1"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.2+0/ITSOL_2.v0.1.2.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[ITSOL_2]]
arch = "x86_64"
git-tree-sha1 = "0745ff954419528f3ddec7ab418f5c4da0d3b28e"
libgfortran_version = "5.0.0"
os = "windows"

    [[ITSOL_2.download]]
    sha256 = "69ae575e27d19217643f545898fa43f4dea72dfa559c04cff0b9ff0c017bce55"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.2+0/ITSOL_2.v0.1.2.x86_64-w64-mingw32-libgfortran5.tar.gz"
