[[ITSOL_2]]
arch = "aarch64"
git-tree-sha1 = "e75443b6b7414e8abf37591bb1463a9e99ce25ae"
libgfortran_version = "5.0.0"
os = "macos"

    [[ITSOL_2.download]]
    sha256 = "b172fe91493c15b2497b0f7acd76bae11ccf7cbc036b7d7702c9f091732c8f6f"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.0+0/ITSOL_2.v0.1.0.aarch64-apple-darwin-libgfortran5.tar.gz"
[[ITSOL_2]]
arch = "aarch64"
git-tree-sha1 = "fbeccb707f106080f4c9bc4a43333508d9d95fca"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "185ecab425c64bdfa10e9c32aeed6abbfc95b72425fce0a82d8f0a02b793fd05"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.0+0/ITSOL_2.v0.1.0.aarch64-linux-gnu-libgfortran3.tar.gz"
[[ITSOL_2]]
arch = "aarch64"
git-tree-sha1 = "ce3bd936cb52316cf9567d5ea03dad13df798b3c"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "8c864da1339a4ff0993ee29b532fc09dc0bc5fc5e28321f61156e5d2dcd7e6d4"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.0+0/ITSOL_2.v0.1.0.aarch64-linux-gnu-libgfortran4.tar.gz"
[[ITSOL_2]]
arch = "aarch64"
git-tree-sha1 = "8e9ccc8997072ebc462cb5ffe0ecfdd62ab155dc"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "ff38eb204110582950c8f6bd03457196ac8cf86b50b44c78453b852b47830460"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.0+0/ITSOL_2.v0.1.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[ITSOL_2]]
arch = "aarch64"
git-tree-sha1 = "1712a99a684ddb4a9adf1c4c113939e867ded7eb"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "d18413c9ca02dbe99db50065daec3bf1aadf7aefd1040eef8fdcb7e82c64bf82"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.0+0/ITSOL_2.v0.1.0.aarch64-linux-musl-libgfortran3.tar.gz"
[[ITSOL_2]]
arch = "aarch64"
git-tree-sha1 = "2e15118cbed5266d492c96ab7482c2fc7c591bc6"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "4d9ca73eb2aaf0c26e515824cf84a1a85cce83f782e6024ed691872a146e4916"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.0+0/ITSOL_2.v0.1.0.aarch64-linux-musl-libgfortran4.tar.gz"
[[ITSOL_2]]
arch = "aarch64"
git-tree-sha1 = "e610a3a25bfb32b8a40c81ce5df2f3e05c94f428"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "99c6c4582927c458148a8794136bb3ab4829c965c97da3224c5bf517fec95967"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.0+0/ITSOL_2.v0.1.0.aarch64-linux-musl-libgfortran5.tar.gz"
[[ITSOL_2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f10952982de09934e966bd3a0f4dcaeaf7a5494e"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "fac1376c3059742532c7d757138b44c25aa266fe9a7ca55d499700892d857b81"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.0+0/ITSOL_2.v0.1.0.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[ITSOL_2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "832fef0d444a8b8bacaeef2fe7d09779983e6ac7"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "4c050616b58310c3463781263467dba4278112bf14a7445e09994e7eb6396d37"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.0+0/ITSOL_2.v0.1.0.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[ITSOL_2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "56c00b51219d7406ffc7011ba66e328cc31bea67"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "463dee3d1bb081756984c9d5f410bcaab47f76f0803badc74e287eadb1f04429"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.0+0/ITSOL_2.v0.1.0.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[ITSOL_2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "258269959a76c1047a5f5ecdbdb3c67dc7b68f14"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "07605a3fadaf1dec4d9a42ef0af915930c2c27d9bc4d83d7ed46c43c15247ee0"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.0+0/ITSOL_2.v0.1.0.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[ITSOL_2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e9fb50909f214e686e0f19c07ef84cd84d20ad54"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "cfbbb296c4ff53eb879a1595afb0a88ea82cd1f4046b3bcec445ad53ef024c80"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.0+0/ITSOL_2.v0.1.0.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[ITSOL_2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8e78c473fb26f4c026a1971debac2a0be88e4217"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "31a95e9d5c157ff7d7d4fd59ba354b65f06ac43a07799d1bd0c8bfd14ef69ff1"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.0+0/ITSOL_2.v0.1.0.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[ITSOL_2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a6c74423008fd78dd80a4408cba62900d071e0f4"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "a3366fb7158d20332dfe409eff6fa2fe5f69020affb6b70146b6d21d681a7873"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.0+0/ITSOL_2.v0.1.0.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[ITSOL_2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f721053cadb5ac727c4022c777e7eca8a87cad3b"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "590a30648711361f1a54e7496349c1540350937739fb285898217b4072411e7f"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.0+0/ITSOL_2.v0.1.0.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[ITSOL_2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0b8101479441187761ff9706d43b4822950f520e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "6109339cce42f3e3f246a6ae54954aeb70ac399a80ecb5f5b9a743dcbad40edc"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.0+0/ITSOL_2.v0.1.0.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[ITSOL_2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "67ac27c231b64964e6f3ed8828fb0be4023c3b99"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "bdfadcb2a96b0d2f36b2f3e73efc5e23c865b2eaa8a00b6a6135846c4e8f174c"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.0+0/ITSOL_2.v0.1.0.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[ITSOL_2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "de3c6808d79fd5e9f32f01e7aeae95f66e531852"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "6b8513a75f4de08cc109a8256084a59c229ae3a8f5a590d55d8dc4755fa79537"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.0+0/ITSOL_2.v0.1.0.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[ITSOL_2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4c45a91ed060d3ab0b60cff980710d9a757679e2"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "4bbbd8e6b810eb122f4edc060fc7a1486f34fa3bdea0813a98970ae5def15d82"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.0+0/ITSOL_2.v0.1.0.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[ITSOL_2]]
arch = "i686"
git-tree-sha1 = "4d27e7f92067242db6bcc5affb4e70c44d549596"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "7feda78bdbc8c12adf54e9c5356bcbbce396ac14fbcd68eb55d00727206f80ab"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.0+0/ITSOL_2.v0.1.0.i686-linux-gnu-libgfortran3.tar.gz"
[[ITSOL_2]]
arch = "i686"
git-tree-sha1 = "fad0be443006ec01cc8f1616b7812f8513bcab47"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "298fa613c7eea6456bd9f74e7e91d42c25b6d6111a8eff4c1110850be8202a50"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.0+0/ITSOL_2.v0.1.0.i686-linux-gnu-libgfortran4.tar.gz"
[[ITSOL_2]]
arch = "i686"
git-tree-sha1 = "b5f47d16d8c859345a510c589d098c14d1729fd0"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "d3276d61092433402295f8d2ab0690c8b00799fa324ff346d3a2269c3418998f"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.0+0/ITSOL_2.v0.1.0.i686-linux-gnu-libgfortran5.tar.gz"
[[ITSOL_2]]
arch = "i686"
git-tree-sha1 = "dd85c7e89222fef87c76c014d032e34da3056055"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "a2d1577f8155cc3ea8ebf32d560786228e933b28e7c74402ac84ce93bb3d2acd"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.0+0/ITSOL_2.v0.1.0.i686-linux-musl-libgfortran3.tar.gz"
[[ITSOL_2]]
arch = "i686"
git-tree-sha1 = "f526fee5de20c410ea2d90543d3c8d8b2fa9bbac"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "5a8137d0ca0bace8c5b3ff7a1de7f9a0f3f9544f735b39c7229340558d9177c0"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.0+0/ITSOL_2.v0.1.0.i686-linux-musl-libgfortran4.tar.gz"
[[ITSOL_2]]
arch = "i686"
git-tree-sha1 = "b036675ce3adfdbff608eaeea29123889bb5d33b"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "ef3137f24c4d6ff8fed0318ddcfeaeb683dade292ef314fe562bb59a670b8904"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.0+0/ITSOL_2.v0.1.0.i686-linux-musl-libgfortran5.tar.gz"
[[ITSOL_2]]
arch = "i686"
git-tree-sha1 = "4c0bf480ba1b9b48d138a5e44b97b5b1b1bf3406"
libgfortran_version = "3.0.0"
os = "windows"

    [[ITSOL_2.download]]
    sha256 = "5295bb121e6a45a06481c0faf872c5fcc8e9ac93ac1a952fc4aceec6d6dd7d31"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.0+0/ITSOL_2.v0.1.0.i686-w64-mingw32-libgfortran3.tar.gz"
[[ITSOL_2]]
arch = "i686"
git-tree-sha1 = "c81fb018304f3153bb04bc161533c36df2173d00"
libgfortran_version = "4.0.0"
os = "windows"

    [[ITSOL_2.download]]
    sha256 = "dd71dc88afbdca9f9fb6c86c8d3a00e8a6ad26af21467ef031f68ad46b7f8c6c"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.0+0/ITSOL_2.v0.1.0.i686-w64-mingw32-libgfortran4.tar.gz"
[[ITSOL_2]]
arch = "i686"
git-tree-sha1 = "726c67a4da8e05df968c6d4bc390c43df6913b98"
libgfortran_version = "5.0.0"
os = "windows"

    [[ITSOL_2.download]]
    sha256 = "26bc628ea0a6e4fe1bb07238bb548d1c4d9379bc1547ed39261eea24fc013bee"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.0+0/ITSOL_2.v0.1.0.i686-w64-mingw32-libgfortran5.tar.gz"
[[ITSOL_2]]
arch = "powerpc64le"
git-tree-sha1 = "e2be997587fee1ab700c4a71e0a53281ef6f5339"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "cf11301a6a92c52f95b72058a782a388077835528ee5ebe19be669dc28f4ad30"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.0+0/ITSOL_2.v0.1.0.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[ITSOL_2]]
arch = "powerpc64le"
git-tree-sha1 = "3c4050baed20c6c5c5ec5f51d7e066f348e69a6f"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "425db6f931c68495d199c8981b4ddc192c7dd363a73b031b0880b0ab1f56176b"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.0+0/ITSOL_2.v0.1.0.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[ITSOL_2]]
arch = "powerpc64le"
git-tree-sha1 = "79ee372f85440d7ee4299b7d735f9cfcfa507dee"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "ac6300ca89dbdaca430ad9b33a2ffd4dd2a03b56c9ee3afc68028ad722478155"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.0+0/ITSOL_2.v0.1.0.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[ITSOL_2]]
arch = "x86_64"
git-tree-sha1 = "21175a97ac689fcd0a2d3f493fe43a6145765508"
libgfortran_version = "3.0.0"
os = "macos"

    [[ITSOL_2.download]]
    sha256 = "24b25c456b634fd7dafa4cbc2c42719026041bfffa838b3aa1df16308a3bf6f0"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.0+0/ITSOL_2.v0.1.0.x86_64-apple-darwin-libgfortran3.tar.gz"
[[ITSOL_2]]
arch = "x86_64"
git-tree-sha1 = "2865c14de64e8246d0c6766a2fafe1f7f518f61b"
libgfortran_version = "4.0.0"
os = "macos"

    [[ITSOL_2.download]]
    sha256 = "9ad5a002dcb60c1574a872eb06aa60fa274afdfaaaddf42ac34d7af18d1168c0"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.0+0/ITSOL_2.v0.1.0.x86_64-apple-darwin-libgfortran4.tar.gz"
[[ITSOL_2]]
arch = "x86_64"
git-tree-sha1 = "1c5eecff7767dbc2cfbf46570d15888ea51c81e5"
libgfortran_version = "5.0.0"
os = "macos"

    [[ITSOL_2.download]]
    sha256 = "d8cb4d79e5e463e66d3ac10925d3cf73c0a030b6237f640d52ab3e3417dfde7a"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.0+0/ITSOL_2.v0.1.0.x86_64-apple-darwin-libgfortran5.tar.gz"
[[ITSOL_2]]
arch = "x86_64"
git-tree-sha1 = "1acb9fdc674c10293a780ec0d7ceac4b037d9760"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "5b23f436957e3c6b67592d0b74a3d02f0fb78086b95f71a819c8722f04f8c24d"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.0+0/ITSOL_2.v0.1.0.x86_64-linux-gnu-libgfortran3.tar.gz"
[[ITSOL_2]]
arch = "x86_64"
git-tree-sha1 = "0ff9d1cf4ea7f8d184cb97e053e9d6e925f2bad1"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "2af35a82474507a9b92fa6048b07a6c74a0a1d8d42128baf9aeb14037064cbff"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.0+0/ITSOL_2.v0.1.0.x86_64-linux-gnu-libgfortran4.tar.gz"
[[ITSOL_2]]
arch = "x86_64"
git-tree-sha1 = "11b457bae768c0eaf950152d8002e5256d93e8fb"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "31e1b3a079f23185db60ec74777941432819046d8c3f683f69d97f0d1bace604"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.0+0/ITSOL_2.v0.1.0.x86_64-linux-gnu-libgfortran5.tar.gz"
[[ITSOL_2]]
arch = "x86_64"
git-tree-sha1 = "e210cf049fc237dfd44dadaa8fb60d0171e21831"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "01f0910025ab4a87ed5ca1572d1e408bd929da9223b4baf108b15becea4a14b1"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.0+0/ITSOL_2.v0.1.0.x86_64-linux-musl-libgfortran3.tar.gz"
[[ITSOL_2]]
arch = "x86_64"
git-tree-sha1 = "ee32895931a399d8525288d1d0ce61a1414572f6"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "ec895611d8cf6b3cc8da0ef493ca8859da9d8e6586df80432d639cbce1ef12b0"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.0+0/ITSOL_2.v0.1.0.x86_64-linux-musl-libgfortran4.tar.gz"
[[ITSOL_2]]
arch = "x86_64"
git-tree-sha1 = "633c0b59ff5cb5b7723bbd5b95e38a3066f393f9"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "bdc8e3fef1ababb192a40988874696b51ed678d6dc49db4ffc8bb9c59ffbda8c"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.0+0/ITSOL_2.v0.1.0.x86_64-linux-musl-libgfortran5.tar.gz"
[[ITSOL_2]]
arch = "x86_64"
git-tree-sha1 = "25cd651e32ca2d715d1332d7f482826ebdd8b03b"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[ITSOL_2.download]]
    sha256 = "bdfa9a0eda4b1a0af56af01bc56dfeb190adaffbdae9b0974155cdf9ebaecc2a"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.0+0/ITSOL_2.v0.1.0.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[ITSOL_2]]
arch = "x86_64"
git-tree-sha1 = "abe2a63b3d320f1c9bc8f13bc72969b6ac8a2ae0"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[ITSOL_2.download]]
    sha256 = "201db5a7d948926660377d94089f6df0ae3db2c7b33688ffe34e35fbe7ccda8b"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.0+0/ITSOL_2.v0.1.0.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[ITSOL_2]]
arch = "x86_64"
git-tree-sha1 = "d3d78d7080d7ee63388b42a4eb06020ebb10bbcb"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[ITSOL_2.download]]
    sha256 = "a2e3c2195958710aa40dd7cb3970a8fe670248e666c602007ad3c205fdba9e6f"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.0+0/ITSOL_2.v0.1.0.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[ITSOL_2]]
arch = "x86_64"
git-tree-sha1 = "a77152784e1386c5750504e0e9d9c4bc06dd29a0"
libgfortran_version = "3.0.0"
os = "windows"

    [[ITSOL_2.download]]
    sha256 = "f4bf77363f95f6ef7330ba3a36bde047bd0f34433c2873a4d1ba07d636d82907"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.0+0/ITSOL_2.v0.1.0.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[ITSOL_2]]
arch = "x86_64"
git-tree-sha1 = "3df2fd3f32558a30160d26b607e50037a43f5e30"
libgfortran_version = "4.0.0"
os = "windows"

    [[ITSOL_2.download]]
    sha256 = "c7c1c94958ab7c01a149e841a76d11068e8957f986eeff9f4eb6ce1a5b8496f9"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.0+0/ITSOL_2.v0.1.0.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[ITSOL_2]]
arch = "x86_64"
git-tree-sha1 = "11cba86fa41d8b7c4dd51eb27b105ad64522e865"
libgfortran_version = "5.0.0"
os = "windows"

    [[ITSOL_2.download]]
    sha256 = "9fbc5392ccaba1bf39aadacdb009f31e309813e0e4fa4d86ea2c7243d022abcc"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.0+0/ITSOL_2.v0.1.0.x86_64-w64-mingw32-libgfortran5.tar.gz"
