[[ITSOL_2]]
arch = "aarch64"
git-tree-sha1 = "41cead90ecb13fd3ac8d3124eadff4c2f03b7d49"
libgfortran_version = "5.0.0"
os = "macos"

    [[ITSOL_2.download]]
    sha256 = "e02361024c67605a0ed0fa590f55e3d1818cb68c10e60b8572b900eec1b941c1"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.1+0/ITSOL_2.v0.1.1.aarch64-apple-darwin-libgfortran5.tar.gz"
[[ITSOL_2]]
arch = "aarch64"
git-tree-sha1 = "dac86fbc353ec1b23c2d53a963cbf731dbb1ad51"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "3c4128f9b98ee28ba32633db3e3cd92ba1e68026a3b4d760ad5f9e7a0775c929"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.1+0/ITSOL_2.v0.1.1.aarch64-linux-gnu-libgfortran3.tar.gz"
[[ITSOL_2]]
arch = "aarch64"
git-tree-sha1 = "f61497a0c72ca304f6a5d681a112b0038e5cc0f0"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "8668044ce70fe01076fc4996e962a0d139eaee521d1bb8ed954cafffb32cb636"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.1+0/ITSOL_2.v0.1.1.aarch64-linux-gnu-libgfortran4.tar.gz"
[[ITSOL_2]]
arch = "aarch64"
git-tree-sha1 = "a80e45a488ac4ce3c162542f32e5284e9776df10"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "17a486fd618f7a3c39ef4ce05ba7d55f42bff6f185b7c45fde1fab9dd0e7d6ef"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.1+0/ITSOL_2.v0.1.1.aarch64-linux-gnu-libgfortran5.tar.gz"
[[ITSOL_2]]
arch = "aarch64"
git-tree-sha1 = "68cf09bba8de8436f946cddf89dab72d1f6297e5"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "8a56543b968fa95739b7d0eac130558ed810f4e77fa47aa3ad2098aa06b4bf0f"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.1+0/ITSOL_2.v0.1.1.aarch64-linux-musl-libgfortran3.tar.gz"
[[ITSOL_2]]
arch = "aarch64"
git-tree-sha1 = "8b696af08ba8849510fb43aa333ee72073d3dee8"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "8b1715da26782ad078cef7545570bb48758aa70bf9da1e51c8584455dbdf279e"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.1+0/ITSOL_2.v0.1.1.aarch64-linux-musl-libgfortran4.tar.gz"
[[ITSOL_2]]
arch = "aarch64"
git-tree-sha1 = "b4a5bedfe9323669fc380d687b745fa16460f3a7"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "be6f0ebedd8a1021cba1b1e0a051888ef751fa9a216337f47f7e863768d0aa4f"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.1+0/ITSOL_2.v0.1.1.aarch64-linux-musl-libgfortran5.tar.gz"
[[ITSOL_2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c872a59c444c02f926e01c126e2b27aadafbecb2"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "29e576b9b51a9c0c665334b4a66655ebebb6066c5551724d6161144276dff999"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.1+0/ITSOL_2.v0.1.1.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[ITSOL_2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5d3cf3b0f1b0f6cc69f355853a71d78d741100a3"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "cea4b0ff8bff9c9c1b1f771b174bfee70af368a982f73924642300df3bb13bf7"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.1+0/ITSOL_2.v0.1.1.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[ITSOL_2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5e7e5e09dbcd7da8d32811242b3aec99ef605705"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "cb6874ca3aef9bf6a75f104848915ae1eb4ca3e39b88c8a3c91870e32e8aa505"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.1+0/ITSOL_2.v0.1.1.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[ITSOL_2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "fa44db8f6a7e0e902cbb76ca58658a9cec9eaff3"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "b4c6869183df2f2366574a7898829442fb6e54e1d0074e1c18e0d5070bf48fa3"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.1+0/ITSOL_2.v0.1.1.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[ITSOL_2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "007b68461a30b457787365c419c0979e57b40ffd"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "e374647d882e9cd5641cc5a6f0f56a03da97862fda7e30fd02b557f5ca9f5f8c"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.1+0/ITSOL_2.v0.1.1.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[ITSOL_2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "055da2f034253af734afa82a2c3b339e947292a9"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "6564f331534bb588f906cd50a68d37e3ae1022cb30c8ae4b55a54a09df2b6570"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.1+0/ITSOL_2.v0.1.1.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[ITSOL_2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c0b0ba3bbc57fe81306158365fba431304cc1ef0"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "13246c5de8c945a5459d9011e5df659fabe05b776b55d14af19e4852983b9045"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.1+0/ITSOL_2.v0.1.1.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[ITSOL_2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0c59d89f226f31f1d1ee029354c16fed8a12b02d"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "1e80c71ad49c2d6ce91fecd0f928fa953dfc85cbecc8ce4e5441ebe9cad2ff4d"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.1+0/ITSOL_2.v0.1.1.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[ITSOL_2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7b7dad340332bc9cec49d03476bc541dce180517"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "50bbf7e7013d7afcf947aeb4c749a2083c68a2961e994077acd2e1f86d8d34c6"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.1+0/ITSOL_2.v0.1.1.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[ITSOL_2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7a509f19045ffbffccd17aa0340ae0e3ae6e2662"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "94a08d936b368049c6302c7fa81b8b500e6f2f3de3496062b0aa3c3ed19c1347"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.1+0/ITSOL_2.v0.1.1.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[ITSOL_2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f8feb8cdf6cc1a27c4fc5130eab3540b9c41d661"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "5fbfce9f08385a06356c6e7b98cec4de54ea3147be80ac57737802de93ff91dd"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.1+0/ITSOL_2.v0.1.1.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[ITSOL_2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "649ab7277167ca4c69b82bffbe17b5b10ad3fd8c"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "b88102d03121d40aa1928de85fbeed07c0e10f9e8a99116852b42eb8d1ae99b8"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.1+0/ITSOL_2.v0.1.1.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[ITSOL_2]]
arch = "i686"
git-tree-sha1 = "47facf0e35e3de5636b05720b9ad8ec17d05a03f"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "79286c4bda6dede0e58d5d303ba0cb7a6d8763914ede16ffa681649963647b7b"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.1+0/ITSOL_2.v0.1.1.i686-linux-gnu-libgfortran3.tar.gz"
[[ITSOL_2]]
arch = "i686"
git-tree-sha1 = "6dd3f88b5c364c472b6f0b8993b094150cb72f75"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "ce3593ee9ba2909b68938f8969d0152966874dedef7fef21a506b68ca67740c7"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.1+0/ITSOL_2.v0.1.1.i686-linux-gnu-libgfortran4.tar.gz"
[[ITSOL_2]]
arch = "i686"
git-tree-sha1 = "a0ee57b3894e73806213d33507b19ac0c938f7de"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "5e9f5aa5c9c1526bce1c45cedd9a8514c2194ea92af21fb69bea85d8b24ad1d6"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.1+0/ITSOL_2.v0.1.1.i686-linux-gnu-libgfortran5.tar.gz"
[[ITSOL_2]]
arch = "i686"
git-tree-sha1 = "801d1aa0533b6fcc3879257e328b4d3451f2e1c5"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "b6a0ad5acd4cdf7ea0ac2b83275a5ca09cb0bc5208169626da86ca31093a6efe"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.1+0/ITSOL_2.v0.1.1.i686-linux-musl-libgfortran3.tar.gz"
[[ITSOL_2]]
arch = "i686"
git-tree-sha1 = "b9407579f88ba00fd80551f95e8d090e08596802"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "5037566e61aadf1454f687b72bc0dd0ddd532b36fb66fceffa194d167aaade07"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.1+0/ITSOL_2.v0.1.1.i686-linux-musl-libgfortran4.tar.gz"
[[ITSOL_2]]
arch = "i686"
git-tree-sha1 = "db8320dc8eb717ab046cc5278dd9bcb651fde87b"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "5e2407bb7c04cd8e3d9ff943daa42a85df22364bfafde09c2a5aeebc1e487eea"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.1+0/ITSOL_2.v0.1.1.i686-linux-musl-libgfortran5.tar.gz"
[[ITSOL_2]]
arch = "i686"
git-tree-sha1 = "bbf4773178cdd979370b69c77854a29fe5ec3eec"
libgfortran_version = "3.0.0"
os = "windows"

    [[ITSOL_2.download]]
    sha256 = "836b37e7f6e6e7f11dcb84f6320adbef4fbc3118fb5c1787994463d81d5ef75d"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.1+0/ITSOL_2.v0.1.1.i686-w64-mingw32-libgfortran3.tar.gz"
[[ITSOL_2]]
arch = "i686"
git-tree-sha1 = "daa07dd575299b602504ea7d6fdd4c693dfe0150"
libgfortran_version = "4.0.0"
os = "windows"

    [[ITSOL_2.download]]
    sha256 = "138261978e9afeee72a0d8673e28eaef67bbcf79392d912036a784ac5e51213d"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.1+0/ITSOL_2.v0.1.1.i686-w64-mingw32-libgfortran4.tar.gz"
[[ITSOL_2]]
arch = "i686"
git-tree-sha1 = "a042a4e8ba7634a2844ff3cc356e8603e6c56c82"
libgfortran_version = "5.0.0"
os = "windows"

    [[ITSOL_2.download]]
    sha256 = "d5ef77f20e84217d25fce41ac12d0dd95aace255b453c3faa3e6b0a27936b2c0"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.1+0/ITSOL_2.v0.1.1.i686-w64-mingw32-libgfortran5.tar.gz"
[[ITSOL_2]]
arch = "powerpc64le"
git-tree-sha1 = "5e2c565e2798157f7701617147b57949a1fc9913"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "b65f4c6078488fe3e313a2aacdddfffa24ab58d0d5cc70597b3eaf5566d78c37"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.1+0/ITSOL_2.v0.1.1.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[ITSOL_2]]
arch = "powerpc64le"
git-tree-sha1 = "bb2923e1ec234cb68cc7204ed6e90406cdb3b50e"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "240e81f122db6eb2c13abb2f9146fa715aed23ca2f97f8d837049c04534522b7"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.1+0/ITSOL_2.v0.1.1.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[ITSOL_2]]
arch = "powerpc64le"
git-tree-sha1 = "dbac678439d8e9e89d8a4c2c354bf90db025b913"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "a3f82143ace9fa5852cafd6255b46eba1587c84b77c89d4efa1fd056bd428edc"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.1+0/ITSOL_2.v0.1.1.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[ITSOL_2]]
arch = "x86_64"
git-tree-sha1 = "e6ad1d0a414ae3c8969df9504bf32458639134c5"
libgfortran_version = "3.0.0"
os = "macos"

    [[ITSOL_2.download]]
    sha256 = "358b1bc773d194b451a941da18e61e97090dc08c366d22951534f2074183ae75"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.1+0/ITSOL_2.v0.1.1.x86_64-apple-darwin-libgfortran3.tar.gz"
[[ITSOL_2]]
arch = "x86_64"
git-tree-sha1 = "903a7bf59dce1cbdf284aba7bba373ddd4946c7e"
libgfortran_version = "4.0.0"
os = "macos"

    [[ITSOL_2.download]]
    sha256 = "66ffba8800a22ad01d250b132f0a2c74b4750bb3113b8c98caf75ed1d81bad34"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.1+0/ITSOL_2.v0.1.1.x86_64-apple-darwin-libgfortran4.tar.gz"
[[ITSOL_2]]
arch = "x86_64"
git-tree-sha1 = "a23f3ccec3e773d7d8f72375269047befe9f64f2"
libgfortran_version = "5.0.0"
os = "macos"

    [[ITSOL_2.download]]
    sha256 = "4b68896b14753db35794e121b6536d98fb7223b7ddd13df2b52b6e911e8bca4f"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.1+0/ITSOL_2.v0.1.1.x86_64-apple-darwin-libgfortran5.tar.gz"
[[ITSOL_2]]
arch = "x86_64"
git-tree-sha1 = "85960a5d8d837c8dc46144d0fdeb226ca1d8bda2"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "50a7df82b1172ed2e42bb98a105bf33120817bca8cc921e58022eef9c79fed6f"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.1+0/ITSOL_2.v0.1.1.x86_64-linux-gnu-libgfortran3.tar.gz"
[[ITSOL_2]]
arch = "x86_64"
git-tree-sha1 = "c94d403dac8d2562fd2f1cc62e1b851eeb1dbcb6"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "584185bb353f5fef0daa69239700f8e399cb3080da3af3eaefc346de92834f7b"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.1+0/ITSOL_2.v0.1.1.x86_64-linux-gnu-libgfortran4.tar.gz"
[[ITSOL_2]]
arch = "x86_64"
git-tree-sha1 = "de684868c58a039fa319eb27033e6c37f971f989"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "69ee3f09bd52bf02e347e5eb5dcf71ceeeff6919cd91b64a2eb1e65936371e65"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.1+0/ITSOL_2.v0.1.1.x86_64-linux-gnu-libgfortran5.tar.gz"
[[ITSOL_2]]
arch = "x86_64"
git-tree-sha1 = "c8ff2e3e548be40e14aa8d8d56945635d424c2d1"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "a8333c04042c35e0eef6f4d75572908f9c07f2c7f005e4a13ad45d245ef79187"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.1+0/ITSOL_2.v0.1.1.x86_64-linux-musl-libgfortran3.tar.gz"
[[ITSOL_2]]
arch = "x86_64"
git-tree-sha1 = "4068bb4ab55eb73e58f6f5460de68d403c77c96a"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "8c4044c092159500f7e98edc886eecba770fd120f9e7173cbd92c47933f09ccf"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.1+0/ITSOL_2.v0.1.1.x86_64-linux-musl-libgfortran4.tar.gz"
[[ITSOL_2]]
arch = "x86_64"
git-tree-sha1 = "44b99b57b71a394af984a31259543d083800233f"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[ITSOL_2.download]]
    sha256 = "140162c5627af3a6f059a71a52c301d2a6977875a4674bf59ad0c3828a46fa03"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.1+0/ITSOL_2.v0.1.1.x86_64-linux-musl-libgfortran5.tar.gz"
[[ITSOL_2]]
arch = "x86_64"
git-tree-sha1 = "7fac6aadf775a2cf64d516befada9fe000af193d"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[ITSOL_2.download]]
    sha256 = "52261997e04c18762b26674b4d86ff54a14878af27f59148b20aa7a9966f6cf4"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.1+0/ITSOL_2.v0.1.1.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[ITSOL_2]]
arch = "x86_64"
git-tree-sha1 = "c20ed94ba3070c3406c7223dc8b91a2067026811"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[ITSOL_2.download]]
    sha256 = "865d04f1d7258a8bf2439d393af74b5e74995e0233f1d6346448b36533964dec"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.1+0/ITSOL_2.v0.1.1.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[ITSOL_2]]
arch = "x86_64"
git-tree-sha1 = "cae37d5932e0f68896422547445240ccb395b3ef"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[ITSOL_2.download]]
    sha256 = "185814b43fd3004303d256531d2ca1fe8dc22f1dc0821c57066469e1e43d632e"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.1+0/ITSOL_2.v0.1.1.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[ITSOL_2]]
arch = "x86_64"
git-tree-sha1 = "467c865f07fe3d08d54c4d4b118ea354b3aeb04c"
libgfortran_version = "3.0.0"
os = "windows"

    [[ITSOL_2.download]]
    sha256 = "0f26a53de0cddeb8cf62971235e60b278bb5758b247ff44d7e46d5f5a2675ed1"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.1+0/ITSOL_2.v0.1.1.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[ITSOL_2]]
arch = "x86_64"
git-tree-sha1 = "8cbedb36f02035bc61389acc7a27bb7661790f0d"
libgfortran_version = "4.0.0"
os = "windows"

    [[ITSOL_2.download]]
    sha256 = "6dd063f02655ba44dc8676beffcdc5208ea5a2a9056a364155de69343de7596b"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.1+0/ITSOL_2.v0.1.1.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[ITSOL_2]]
arch = "x86_64"
git-tree-sha1 = "47b83cb89f665c421af3a05420f2b43ef948c6ee"
libgfortran_version = "5.0.0"
os = "windows"

    [[ITSOL_2.download]]
    sha256 = "8998ba431d5bd3b535bf79ba498a6d1892510b71f19f58baa190e77283825278"
    url = "https://github.com/JuliaBinaryWrappers/ITSOL_2_jll.jl/releases/download/ITSOL_2-v0.1.1+0/ITSOL_2.v0.1.1.x86_64-w64-mingw32-libgfortran5.tar.gz"
